// This file is automatically generated

#pragma warning disable CS8618
#pragma warning disable CS0219

using CyberpunkSdk;
using CyberpunkSdk.Types;

using CyberpunkSdk.Systems;

using CyberpunkSdk.Internal;

namespace Cyberpunk.Rpc.Server.Plugins
{
public static partial class CoopServer
{
	[ServerRpc(Class = 7467838127638521499, Function = 592915393019958081)]
	public static void ReportWorld(ulong playerId, IBuffer data)
	{
		ushort length = 0;
		var gameTime = data.ReadInt32();
		var weather = new CName(data.ReadUint64());
		var quest = data.ReadString();

		ReportWorld_Impl(playerId, gameTime, weather, quest);
	}

	public static partial void ReportWorld_Impl(ulong playerId, int gameTime, CName weather, string quest);

	[ServerRpc(Class = 7467838127638521499, Function = 10081915271799181938)]
	public static void Command(ulong playerId, IBuffer data)
	{
		ushort length = 0;
		var text = data.ReadString();

		Command_Impl(playerId, text);
	}

	public static partial void Command_Impl(ulong playerId, string text);

}
}
