// This file is automatically generated

#pragma warning disable CS8618
#pragma warning disable CS0219

using CyberpunkSdk;
using CyberpunkSdk.Types;

using CyberpunkSdk.Systems;

using CyberpunkSdk.Internal;

namespace Cyberpunk.Rpc.Client.Plugins
{
public static class CoopClient
{
	[ClientRpc(Class = 2305192715875678463, Function = 4097336381882062765)]
	public static void SetRole(ulong playerId, bool isHost, string hostName)
	{
		ushort length = 0;
		var data = IBuffer.Create();
		try{
			data.WriteBool(isHost);
			data.WriteString(hostName);
			CyberpunkSdk.Server.RpcManager.Call(playerId, 2305192715875678463, 4097336381882062765, data);
		} finally {
			IBuffer.Release(data);
		}
	}

	[ClientRpc(Class = 2305192715875678463, Function = 12379067423272437681)]
	public static void ApplyWorld(ulong playerId, int gameTime, CName weather, string quest)
	{
		ushort length = 0;
		var data = IBuffer.Create();
		try{
			data.WriteInt32(gameTime);
			data.WriteUint64(weather.Hash);
			data.WriteString(quest);
			CyberpunkSdk.Server.RpcManager.Call(playerId, 2305192715875678463, 12379067423272437681, data);
		} finally {
			IBuffer.Release(data);
		}
	}

	[ClientRpc(Class = 2305192715875678463, Function = 10686465332880473962)]
	public static void TeleportTo(ulong playerId, float x, float y, float z)
	{
		ushort length = 0;
		var data = IBuffer.Create();
		try{
			data.WriteFloat(x);
			data.WriteFloat(y);
			data.WriteFloat(z);
			CyberpunkSdk.Server.RpcManager.Call(playerId, 2305192715875678463, 10686465332880473962, data);
		} finally {
			IBuffer.Release(data);
		}
	}

}
}
